### ISSUE TITLE
Panic computing BitListHTR when too long

### ISSUE THREAD

**Issue by Mario-DLH** [protolambda/ztyp#2]
I'm trying to compute the htr of a beacon block sample but it panics when trying to compute the HTR of a bitlist field ("aggregation_bits": "0xae44a59e9b57b7141da75dba9d385b795ba84317f41948621bf98a34f92168838b72a9678bc58de000cf466104613975fb1490c591f0ee9055cce4aaa2ff0eb5a26c8b9e20b6a386d9e9f7964a3ebb957e3c6b0124271c279496235101a29fbf18ac7be6749a8b1f230bb5131e97b28c06683ca9a6cb6129b2a25b4f539f7f5e41cc1997c5b4a57d51dbce5ad4ab746a403e5270c785b76d47475c0ee6c309e33dad08193c3f8e40e9414096276bfb5708c84359dd51eb54ca67dd7a6eb5645801fb83811b4c11eb5b240e9d0bc0847ae7abfa235c7d6cc5f7eca53bce62b1b987b7c11ef54592399882d7983eb3c6a58ff636f52b4007afbc0d66bfe9d9276a01"), specifically in this [line](https://github.com/protolambda/ztyp/blob/862a3e92e3714268ef42f41b493d5c774c5651ef/tree/hashing.go#L153). It panics giving this error when i = 2: `panic: runtime error: slice bounds out of range [512:257]`.

**Comment by protolambda** [comment]
Nice catch, fixed in https://github.com/protolambda/ztyp/commit/07415f7d6efe970e52af9e47ed9320be0549ba9f, will update ZRNT too.

**Comment by protolambda** [comment]
new releases with fix: ZTYP v0.2.2, ZRNT v0.26.1 and ZCLI v0.4.2
Thanks :clap:
